import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: "http://res.cloudinary.com/dwhran9qg/image/upload/Cricket/ball_woy6oc.jpg",
    name: "NX Cricket Ball White - Season Ball ",
    price: 2999,
    rating: 3.7,
    stock: "In Stock",
    delivery: "Fast Delivery",
    categoryName: "Cricket",
  },

  {
    _id: uuid(),
    img: "http://res.cloudinary.com/dwhran9qg/image/upload/Fitness Accessories/Yoga_mat_hn8ctw.jpg",
    name: "Stag Yoga Mantra Asana Mat (6MM)",
    price: 1050,
    rating: 3.1,
    stock: "Out Of Stock",
    delivery: "minimum 3 days",
    categoryName: "Fitness Accessories",
  },
  {
    _id: uuid(),
    img: "http://res.cloudinary.com/dwhran9qg/image/upload/Active Wear/T-shirt_uhzcco.jpg",
    name: "GM Cricket Men's Full T-Shirt",
    price: 1999,
    rating: 4.1,
    stock: "Out of Stock",
    delivery: "Fast Delivery",
    categoryName: "Active Wear",
  },
  {
    _id: uuid(),
    img: "http://res.cloudinary.com/dwhran9qg/image/upload/Fitness Accessories/Rope_nolt1p.jpg",
    name: "Body Sculpture Skip Rope With Counter",
    price: 749,
    rating: 3.5,
    stock: "In Stock",
    delivery: "minimum 3 days",
    categoryName: "Fitness Accessories",
  },
  {
    _id: uuid(),
    img: "http://res.cloudinary.com/dwhran9qg/image/upload/Fitness Equipments/Treadmill_xbrvqy.jpg",
    name: "Powermax TDA-600 Motorized Treadmill",
    price: 9000,
    rating: 2.9,
    stock: "In Stock",
    delivery: "Fast Delivery",
    categoryName: "Fitness Equipment",
  },
  {
    _id: uuid(),
    img: "http://res.cloudinary.com/dwhran9qg/image/upload/Football/Shoes_boecfy.jpg",
    name: "Nike Bravata II FG Football Shoes",
    price: 3495,
    rating: 4.6,
    stock: "Out of Stock",
    delivery: "minimum 3 days",
    categoryName: "Football",
  },
  {
    _id: uuid(),
    img: "http://res.cloudinary.com/dwhran9qg/image/upload/Active Wear/Tracksuit_tfypbu.jpg",
    name: "Yonex Track Suit (78037 - Jet Blue)",
    price: 4224,
    rating: 3.4,
    stock: "In Stock",
    delivery: "Fast Delivery",
    categoryName: "Active Wear",
  },
  {
    _id: uuid(),
    img: "http://res.cloudinary.com/dwhran9qg/image/upload/Cricket/Cricket_kit_mqckys.jpg",
    name: "DSC Premium Cricket Set",
    price: 5299,
    rating: 4.2,
    stock: "In Stock",
    delivery: "minimum 3 days",
    categoryName: "Cricket",
  },
  {
    _id: uuid(),
    img: "https://res.cloudinary.com/dwhran9qg/image/upload/Fitness Equipments/Cardio_equipment_pw3rif.jpg",
    name: "Powermax GB 110 SX Bike With Back Rest",
    price: 9890,
    rating: 1.9,
    stock: "Out of Stock",
    delivery: "minimum 3 days",
    categoryName: "Fitness Equipment",
  },
  {
    _id: uuid(),
    img: "http://res.cloudinary.com/dwhran9qg/image/upload/Football/Football_jnjmua.jpg",
    name: "Adidas FIFA World Cup 2018 OMB Football",
    price: 2499,
    rating: 4.4,
    stock: "In Stock",
    delivery: "Fast Delivery",
    categoryName: "Football",
  },
];
